version: "3.7"
services:
  vault:
    image: vault:1.4.2
    container_name: vault
    hostname: vault
    ports:
      - 8200:8200
    volumes:
      - ./config.hcl:/vault/config/config.hcl
      - /var/www/vault/data:/vault/file/
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: server
    restart: always
    networks:
      - internal

  vault-init:
    image: vault:1.4.2
    container_name: vault-init
    environment:
      - VAULT_ADDR=http://1.2.3.4:8200
      - MY_VAULT_TOKEN=my-secure-token
    volumes:
      - ./vault-root-token:/vault/file/vault-root-token
      - ./vault-init.sh:/usr/local/bin/vault-init.sh
      - /var/www/vault/data:/vault/file/
      - /domain/certs:/vault/certs/
    command: /usr/local/bin/vault-init.sh
    restart: on-failure
    networks:
      - internal
    depends_on:
      - vault
    links:
      - vault
networks:
  internal:
    driver: bridge
    enable_ipv6: false